---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: app
data:
  config.json: |
    {
      "auto_auth": {
        "method": {
          "type": "kubernetes",
          "mount_path": "auth/kubernetes",
          "config": {
            "role": "app"
          }
        },
        "sink": [
          {
            "type": "file",
            "config": {
              "path": "/home/vault/.vault-token"
            }
          }
        ]
      },
      "exit_after_auth": false,
      "pid_file": "/tmp/.pid",
      "template": [
        {
          "destination": "/vault/secrets/db-creds",
          "contents": "{{- with secret \"database/creds/db-app\" -}}\npostgres://{{ .Data.username }}:{{ .Data.password }}@postgres.postgres.svc:5432/wizard?sslmode=disable\n{{- end }}\n",
          "left_delimiter": "{{",
          "right_delimiter": "}}",
          "command": "sh -c 'kill -HUP $(pidof app)'"
        }
      ]
    }
  config-init.json: |
    {
      "auto_auth": {
        "method": {
          "type": "kubernetes",
          "mount_path": "auth/kubernetes",
          "config": {
            "role": "app"
          }
        },
        "sink": [
          {
            "type": "file",
            "config": {
              "path": "/home/vault/.vault-token"
            }
          }
        ]
      },
      "exit_after_auth": true,
      "pid_file": "/tmp/.pid",
      "template": [
        {
          "destination": "/vault/secrets/db-creds",
          "contents": "{{- with secret \"database/creds/db-app\" -}}\npostgres://{{ .Data.username }}:{{ .Data.password }}@postgres.postgres.svc:5432/wizard?sslmode=disable\n{{- end }}\n",
          "left_delimiter": "{{",
          "right_delimiter": "}}",
          "command": "sh -c 'kill -HUP $(pidof app)'"
        }
      ]
    }
